name: tv
description: "A new Flutter package project."

publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.7.0 <=4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core

  http: ^1.2.2
  provider: ^6.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.4.1
  get_it: ^7.7.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  firebase_core: ^3.10.1
  firebase_analytics: ^11.4.1
  firebase_crashlytics: ^4.3.1
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.8
  build_runner: ^2.0.4
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/certificates/certificates.pem